use_frameworks!

platform :ios, '10.0'

target 'CLCScrollViewIndicator_Example' do
  pod 'CLCScrollViewIndicator', :path => '../'

  target 'CLCScrollViewIndicator_Tests' do
    inherit! :search_paths

    
  end
end
